apiVersion: v1
kind: Service
metadata:
  name: vm-management-backend-service
spec:
  selector:
    app: vm-management-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer